### ISSUE TITLE
Stopping translating

### ISSUE THREAD

**Issue by OLucasDiniz** [duc010298-1/translate-renpy#10]
Hi, how are you, you know why this "error" is happening, all the time I have to press enter to continue, do you know how to fix it?

Note: I already checked my internet and it's ok

![image](https://user-images.githubusercontent.com/89727941/131245978-7a07ddb5-7dd3-47ad-88b9-02a7f7592536.png)

**Comment by duc010298-1** [comment]
Hi @OLucasDiniz 

This is a known error, it occurs because you have exceeded the rate limit of Google translate. If you try going to https://translate.google.com/ and try to translate a word, you will get nothing. Google has blocked you from using their service. You will only be able to use the service again if you change your machine's public IP or wait until the ban is lifted

I am currently developing another version that aims to fix this problem with the help of VPN.

**Comment by OLucasDiniz** [comment]
Thanks for the information, is there any way to know how long I was banned?

**Comment by OLucasDiniz** [comment]
Sorry for my English, I'm Brazilian hahahaha

**Comment by duc010298-1** [comment]
> Thanks for the information, is there any way to know how long I was banned?

Currently, I also do not know the exact time for google to remove the ban. 
But you can try resetting your apartment's internet modem. In most cases you will get a new public ip address. This will get you out of the ban.

**Comment by OLucasDiniz** [comment]
I get it, but I hope that when my ban goes out, I don't get banned fast again.

**Comment by OLucasDiniz** [comment]
Could you give a date when this new script of yours with vpn will be ready?

**Comment by duc010298-1** [comment]
Sorry I can't give an exact release date for the new version at the moment. This new version won't be ready until at least next weekend, you can watch this repo to get updates as soon as the new version is ready.

This new version includes refactoring of the source code, improved performance, along with an important option that allows you to continue the translation process without having to start over, in case the previous run fails.

**Comment by OLucasDiniz** [comment]
My God, this is amazing I will be waiting for this new update for sure :)

**Comment by duc010298-1** [comment]
Hi @OLucasDiniz 

I just updated the latest version for this tool, you can try it now.

The current guide may not be complete, I will try to update it as soon as possible
