### ISSUE TITLE
Stopping translating again

### ISSUE THREAD

**Issue by OLucasDiniz** [duc010298-1/translate-renpy#11]
Hello I downloaded the new update and it still has the same error :(

![image](https://user-images.githubusercontent.com/89727941/132120181-84344bf6-b2a8-4139-955d-be5112c82e3e.png)

**Comment by duc010298-1** [comment]
Hi @OLucasDiniz 

Please try to go to https://translate.google.com/ with your browser and try to translate a word, if you can't translate then you have exceeded google's rate limit.

The only solution here is to try to change your public IP address by resetting your internet modem or using a VPN. In case you are using vpn, I would recommend using Windscribe.

My tool will support you to continue translating from your previous attempt so if you exceed google rate limit, just connect to another vpn address and relaunch the tool

**Comment by duc010298-1** [comment]
I find it quite strange that you've only translated 182 phrases that have already exceeded the rate limit. I often get banned when I finish translating 4000 to 5000 phrases with 16 threads

**Comment by OLucasDiniz** [comment]
Even though I exceeded the google rate limit for your program, I still managed to continue translating through https://translate.google.com/ I'm finding this very strange...

![image](https://user-images.githubusercontent.com/89727941/132125890-47194558-552c-472d-a0cf-9da2a30fc049.png)

**Comment by OLucasDiniz** [comment]
![image](https://user-images.githubusercontent.com/89727941/132126134-d5cf6857-5fd4-4730-8fcc-3180963b82ec.png)
Even with the vpn that you refer me, it only translates a hundred and a few words and then stops again

**Comment by OLucasDiniz** [comment]
![image](https://user-images.githubusercontent.com/89727941/132126229-ef5cc6b6-ca65-4f1a-a3b2-80b02c20c59a.png)
You can see that the error occurred again, but even with the error it's translating, I'll leave it that way, if it works it's even better kkkkk

**Comment by duc010298-1** [comment]
Can you give me your hardware information? CPU, Ram, SSD

Try running with a lower thread count to see if the problem improves. I mean try with 4 or 6 threads

**Comment by duc010298-1** [comment]
Hi @OLucasDiniz

Today I tried running the tool again on a slow and unstable internet connection and I had a similar situation as you described. 

I just modified some parameters of the tool to fix this situation. You can download and try again.

**Comment by OLucasDiniz** [comment]
Sorry for the delay, I downloaded the new update and when I try to run it goes in and out at the same time

**Comment by NoDoon** [comment]
![image](https://user-images.githubusercontent.com/66499633/146473261-088ad149-b027-40e5-b1e6-7b5ca8bc6e79.png)
Hello, Google Translate works for me, but your code doesn't work. My computer is 16G RAM and i710th. Have you ever come across a situation like this？

**Comment by duc010298-1** [comment]
Hi @NoDoon 

I just checked and found out that Google has updated the layout of https://translate.google.com/. I just updated the code. I haven't had time to test it yet, you can try it again now and please let me know if the error is still there

**Comment by duc010298-1** [comment]
Hi @NoDoon 

I just re-tested the code, everything is working normally again, please get the v1.2 code and use it. Please let me know if there are any other errors

**Comment by NoDoon** [comment]
Thank you very much, it's working now. But I don't know why, when I run this code the first time, the cmd always closes automatically without showing the process, when I open it the second time it works

**Comment by NoDoon** [comment]
Stars for you, thanks again, because I tried to write my own code and had all sorts of problems

**Comment by duc010298-1** [comment]
> Thank you very much, it's working now. But I don't know why, when I run this code the first time, the cmd always closes automatically without showing the process, when I open it the second time it works

It didn't happen to me but I will try to reproduce bug and fix it if it really is
