### ISSUE TITLE
Network issues (gender specific?)

### ISSUE THREAD

**Issue by toertchn** [duc010298-1/translate-renpy#16]
I try to translate from english to german.
Most times it says: Translation was stopped because the issue of network

The Chrome Windows seems to continue in the background so I'm not sure what this is.

Can it be the german gender specific translation results?
Example:
https://translate.google.com/?hl=en&sl=en&tl=de&text=Buddy%3F&op=translate

![image](https://user-images.githubusercontent.com/75972576/173499434-a0d4e381-b172-40d0-a581-2d3f0c7a596b.png)

**Comment by duc010298-1** [comment]
Thank you so much for pointing this out, I'll fix it as soon as possible

**Comment by duc010298-1** [comment]
Hi @toertchn 
I have fixed this issues, you can check ver 1.6 to get the latest code
