### ISSUE TITLE
（Translation was stopped because the issue of network）still there

### ISSUE THREAD

**Issue by AyaSwan** [duc010298-1/translate-renpy#17]
First Attempt A project yesterday and finishing the translation. Today i open the next one again, the site（google translate） opens, but does not translate(Where there are words do not show, just open the site like that), and After a while, 1.6 shows a Google Translate timeout.

Is that because Google translate queries the same IP over a short period of time caused by excessive translation?

Thank you for your software

**Comment by duc010298-1** [comment]
Yep, it is google rate limit problem, i have not found a solution to solve this problem. 
In the short term, you can use vpn to continue translating until the project is completed

**Comment by AyaSwan** [comment]
thank you for your reply.
