### ISSUE TITLE
problem sorry

### ISSUE THREAD

**Issue by turpez** [duc010298-1/translate-renpy#6]
after a while its me but its i do what?

Translation was stopped because the issue of network
Press Enter to try again...

**Comment by duc010298-1** [comment]
You seem to exceed google translate request limits. Google will block your access to Google translate.

I'm not sure exactly what the limit is, google doesn't make this public. The only thing you can do now is find a way to change your network IP, maybe reset your router or use vpn... Try again but don't open too many threads at once.

You can also split your rpy files into multiple directories and translate each of them, this ensures you retain what you translated before being blocked from google translate access.

**Comment by turpez** [comment]
even do it while i'm using a single thread

**Comment by turpez** [comment]
If I use a vpn will it put me at all ?

**Comment by duc010298-1** [comment]
> If I use a vpn will it put me at all ?

Yeb, this is the risk you have to trade off trying to translate too much at once. Google blocks such access to prevent automated tools from acting. Instead, they direct users to use paid services like Google Translate Api
