### ISSUE TITLE
One problem

### ISSUE THREAD

**Issue by mstf01** [duc010298-1/translate-renpy#8]
Hello

Thank you for code

I ran into such a problem

![Ekran görüntüsü 2021-08-23 000412](https://user-images.githubusercontent.com/89359760/130370158-3934f543-b406-4ea0-8f06-4bb9eafa5ffc.png)

**Comment by duc010298-1** [comment]
Thanks for the report, I'll try to fix it as soon as possible

**Comment by duc010298-1** [comment]
Hi @mstf01 

The problem has been resolved, please get the latest source code to use.

**Comment by mstf01** [comment]
Hi

Thank you.


Again, I've encountered errors.

![Ekran görüntüsü 2021-08-23 173453](https://user-images.githubusercontent.com/89359760/130468680-a723a406-1239-487d-a323-1277b0c8f734.png)
![Ekran görüntüsü 2021-08-23 173629](https://user-images.githubusercontent.com/89359760/130468682-4b1b72e4-ce75-4e6d-a622-902c59070889.png)
![Ekran görüntüsü 2021-08-23 174822](https://user-images.githubusercontent.com/89359760/130468686-10c82b68-2488-40e9-b8d7-2a18c20d7eb8.png)
![Ekran görüntüsü 2021-08-23 175011](https://user-images.githubusercontent.com/89359760/130468687-136644d9-992c-4ddb-9f15-fe75c8348a7f.png)
![Ekran görüntüsü 2021-08-23 175037](https://user-images.githubusercontent.com/89359760/130468689-115ea892-02c7-4ae1-9f15-ae358cd6be54.png)

**Comment by duc010298-1** [comment]
Hi @mstf01,
I just fixed it again, please let me know if you encounter any similar problem like this again

**Comment by mstf01** [comment]
Hi

Thank you.

If I run into problems again, I'll let you know.

Good luck with
